using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MapApp.Domain.Dto
{
    internal class AddressDto
    {
    }
    /*X,Y,OBJECTID,ADDRESS_ID,STREET_AREA,STREET_NUM,STREET_PREFIX_DIR,STREET_NAME,STREET_TYPE,STREET_SUFFIX_DIR,APARTMENT_NUM,MUNICIPALITY,STATE,ZIPCODE,ZIPCODE_SUF,UNINC_INC,COUNTY,ESN,LOCATION1,LOCATION2,LOCATION3,LOCATION4,COMMON_NAME,FEATURE_CLASS_CODE,MESSAGE,PIN,NOTES,DATA_SOURCE,MULTIPIN_PRIMARYPIN,MULTIPIN_LOWPIN,MULTIPIN_PINCOUNT,BOOK_DISCREPANCY,BOOK_ADDRESS,BOOK_UPDATE,ADDRESS_NUM,dmNotesXML,dmValidation,dmClientUploadedFileID,created_user,created_date,last_edited_user,last_edited_date,GlobalID,ADDRESS_TYPE,PROPADDRL1,PROPADDRL2,PROPSTREETNUM,ANGLE,POINT_X,POINT_Y*/
}
